In [1]:
from fastai.vision.all import *
from fastbook import *
from fastai.vision.widgets import *


### Creating a Tensor

In [2]:
data = [[1, 2, 3], [4, 5, 6]]
arr = array(data)
print(type(arr))
tns = tensor(data)
print(type(tns))


<class 'numpy.ndarray'>
<class 'torch.Tensor'>


Arrays in the tensor must be of the same length 

In [4]:
tensor([[1, 2], [3, 4], [1, 2, 3, 4, 5]])


ValueError: expected sequence of length 2 at dim 1 (got 5)

### Some operations with tensors

In [7]:
tns


tensor([[1, 2, 3],
        [4, 5, 6]])

In [5]:
tns[1]


tensor([4, 5, 6])

In [6]:
tns[:, 1]


tensor([2, 5])

In [9]:
tns[1, 1:3]


tensor([5, 6])

In [11]:
tns + 10  # / * - +


tensor([[11, 12, 13],
        [14, 15, 16]])

Tensors automatically change their data type

In [12]:
tns.type()


'torch.LongTensor'

In [15]:
tns*1.5


tensor([[1.5000, 3.0000, 4.5000],
        [6.0000, 7.5000, 9.0000]])

In [14]:
(tns*1.5).type()


'torch.FloatTensor'

The most important PyTorch technique

In [16]:
tensor([1, 2, 3]) + tensor([1, 1, 1])


tensor([2, 3, 4])